name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Black formatting
        uses: actions/checkout@v2
        uses: psf/black@stable
      - name: pydocstyle
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle
          pydocstyle versioned-pickle/